# Generated by Django 4.1.12 on 2023-12-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_file_avator_remove_file_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="avator",
            new_name="avatar",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="avator",
            new_name="avatar",
        ),
        migrations.AlterField(
            model_name="file",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="Products/"),
        ),
    ]
