# Generated by Django 4.1.12 on 2023-12-16 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_rename_avator_category_avatar_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="Categories",
        ),
    ]
