# Generated by Django 4.1.12 on 2023-12-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_category_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="Files/"),
        ),
    ]
